// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class EmployeeCarrierRelation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeCarrierRelationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EmployeeCarrierRelation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		Region("Region"),
		EmployeeCarrierRelation_Carrier("MyFirstModule.EmployeeCarrierRelation_Carrier"),
		EmployeeCarrierRelation_Employee("MyFirstModule.EmployeeCarrierRelation_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeeCarrierRelation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.EmployeeCarrierRelation"));
	}

	protected EmployeeCarrierRelation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeCarrierRelationMendixObject)
	{
		if (employeeCarrierRelationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.EmployeeCarrierRelation", employeeCarrierRelationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.EmployeeCarrierRelation");

		this.employeeCarrierRelationMendixObject = employeeCarrierRelationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmployeeCarrierRelation.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.EmployeeCarrierRelation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.EmployeeCarrierRelation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.EmployeeCarrierRelation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EmployeeCarrierRelation(context, mendixObject);
	}

	public static myfirstmodule.proxies.EmployeeCarrierRelation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EmployeeCarrierRelation.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.EmployeeCarrierRelation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.EmployeeCarrierRelation> result = new java.util.ArrayList<myfirstmodule.proxies.EmployeeCarrierRelation>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.EmployeeCarrierRelation" + xpathConstraint))
			result.add(myfirstmodule.proxies.EmployeeCarrierRelation.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Description
	 */
	public final String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final myfirstmodule.proxies.Region getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final myfirstmodule.proxies.Region getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Region.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Region.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(myfirstmodule.proxies.Region region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Region region)
	{
		if (region != null)
			getMendixObject().setValue(context, MemberNames.Region.toString(), region.toString());
		else
			getMendixObject().setValue(context, MemberNames.Region.toString(), null);
	}

	/**
	 * @return value of EmployeeCarrierRelation_Carrier
	 */
	public final myfirstmodule.proxies.Carrier getEmployeeCarrierRelation_Carrier() throws com.mendix.core.CoreException
	{
		return getEmployeeCarrierRelation_Carrier(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeCarrierRelation_Carrier
	 */
	public final myfirstmodule.proxies.Carrier getEmployeeCarrierRelation_Carrier(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Carrier result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeCarrierRelation_Carrier.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Carrier.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EmployeeCarrierRelation_Carrier
	 * @param employeecarrierrelation_carrier
	 */
	public final void setEmployeeCarrierRelation_Carrier(myfirstmodule.proxies.Carrier employeecarrierrelation_carrier)
	{
		setEmployeeCarrierRelation_Carrier(getContext(), employeecarrierrelation_carrier);
	}

	/**
	 * Set value of EmployeeCarrierRelation_Carrier
	 * @param context
	 * @param employeecarrierrelation_carrier
	 */
	public final void setEmployeeCarrierRelation_Carrier(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Carrier employeecarrierrelation_carrier)
	{
		if (employeecarrierrelation_carrier == null)
			getMendixObject().setValue(context, MemberNames.EmployeeCarrierRelation_Carrier.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EmployeeCarrierRelation_Carrier.toString(), employeecarrierrelation_carrier.getMendixObject().getId());
	}

	/**
	 * @return value of EmployeeCarrierRelation_Employee
	 */
	public final myfirstmodule.proxies.Employee getEmployeeCarrierRelation_Employee() throws com.mendix.core.CoreException
	{
		return getEmployeeCarrierRelation_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeCarrierRelation_Employee
	 */
	public final myfirstmodule.proxies.Employee getEmployeeCarrierRelation_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeCarrierRelation_Employee.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EmployeeCarrierRelation_Employee
	 * @param employeecarrierrelation_employee
	 */
	public final void setEmployeeCarrierRelation_Employee(myfirstmodule.proxies.Employee employeecarrierrelation_employee)
	{
		setEmployeeCarrierRelation_Employee(getContext(), employeecarrierrelation_employee);
	}

	/**
	 * Set value of EmployeeCarrierRelation_Employee
	 * @param context
	 * @param employeecarrierrelation_employee
	 */
	public final void setEmployeeCarrierRelation_Employee(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Employee employeecarrierrelation_employee)
	{
		if (employeecarrierrelation_employee == null)
			getMendixObject().setValue(context, MemberNames.EmployeeCarrierRelation_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EmployeeCarrierRelation_Employee.toString(), employeecarrierrelation_employee.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeCarrierRelationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EmployeeCarrierRelation that = (myfirstmodule.proxies.EmployeeCarrierRelation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.EmployeeCarrierRelation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
