// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class TransientIncidentPivotTableCell
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transientIncidentPivotTableCellMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.TransientIncidentPivotTableCell";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		categoryNumber("categoryNumber"),
		categoryName("categoryName"),
		carrierNumber("carrierNumber"),
		carrierName("carrierName"),
		TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters("MyFirstModule.TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransientIncidentPivotTableCell(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.TransientIncidentPivotTableCell"));
	}

	protected TransientIncidentPivotTableCell(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transientIncidentPivotTableCellMendixObject)
	{
		if (transientIncidentPivotTableCellMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.TransientIncidentPivotTableCell", transientIncidentPivotTableCellMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.TransientIncidentPivotTableCell");

		this.transientIncidentPivotTableCellMendixObject = transientIncidentPivotTableCellMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransientIncidentPivotTableCell.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TransientIncidentPivotTableCell initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.TransientIncidentPivotTableCell.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TransientIncidentPivotTableCell initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TransientIncidentPivotTableCell(context, mendixObject);
	}

	public static myfirstmodule.proxies.TransientIncidentPivotTableCell load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TransientIncidentPivotTableCell.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of categoryNumber
	 */
	public final java.lang.Long getcategoryNumber()
	{
		return getcategoryNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of categoryNumber
	 */
	public final java.lang.Long getcategoryNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.categoryNumber.toString());
	}

	/**
	 * Set value of categoryNumber
	 * @param categorynumber
	 */
	public final void setcategoryNumber(java.lang.Long categorynumber)
	{
		setcategoryNumber(getContext(), categorynumber);
	}

	/**
	 * Set value of categoryNumber
	 * @param context
	 * @param categorynumber
	 */
	public final void setcategoryNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long categorynumber)
	{
		getMendixObject().setValue(context, MemberNames.categoryNumber.toString(), categorynumber);
	}

	/**
	 * @return value of categoryName
	 */
	public final java.lang.String getcategoryName()
	{
		return getcategoryName(getContext());
	}

	/**
	 * @param context
	 * @return value of categoryName
	 */
	public final java.lang.String getcategoryName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.categoryName.toString());
	}

	/**
	 * Set value of categoryName
	 * @param categoryname
	 */
	public final void setcategoryName(java.lang.String categoryname)
	{
		setcategoryName(getContext(), categoryname);
	}

	/**
	 * Set value of categoryName
	 * @param context
	 * @param categoryname
	 */
	public final void setcategoryName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String categoryname)
	{
		getMendixObject().setValue(context, MemberNames.categoryName.toString(), categoryname);
	}

	/**
	 * @return value of carrierNumber
	 */
	public final java.lang.Long getcarrierNumber()
	{
		return getcarrierNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of carrierNumber
	 */
	public final java.lang.Long getcarrierNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.carrierNumber.toString());
	}

	/**
	 * Set value of carrierNumber
	 * @param carriernumber
	 */
	public final void setcarrierNumber(java.lang.Long carriernumber)
	{
		setcarrierNumber(getContext(), carriernumber);
	}

	/**
	 * Set value of carrierNumber
	 * @param context
	 * @param carriernumber
	 */
	public final void setcarrierNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long carriernumber)
	{
		getMendixObject().setValue(context, MemberNames.carrierNumber.toString(), carriernumber);
	}

	/**
	 * @return value of carrierName
	 */
	public final java.lang.String getcarrierName()
	{
		return getcarrierName(getContext());
	}

	/**
	 * @param context
	 * @return value of carrierName
	 */
	public final java.lang.String getcarrierName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.carrierName.toString());
	}

	/**
	 * Set value of carrierName
	 * @param carriername
	 */
	public final void setcarrierName(java.lang.String carriername)
	{
		setcarrierName(getContext(), carriername);
	}

	/**
	 * Set value of carrierName
	 * @param context
	 * @param carriername
	 */
	public final void setcarrierName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carriername)
	{
		getMendixObject().setValue(context, MemberNames.carrierName.toString(), carriername);
	}

	/**
	 * @return value of TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters
	 */
	public final myfirstmodule.proxies.TransientIncidentPivotTableParameters getTransientIncidentPivotTableCell_TransientIncidentPivotTableParameters() throws com.mendix.core.CoreException
	{
		return getTransientIncidentPivotTableCell_TransientIncidentPivotTableParameters(getContext());
	}

	/**
	 * @param context
	 * @return value of TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters
	 */
	public final myfirstmodule.proxies.TransientIncidentPivotTableParameters getTransientIncidentPivotTableCell_TransientIncidentPivotTableParameters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.TransientIncidentPivotTableParameters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.TransientIncidentPivotTableParameters.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters
	 * @param transientincidentpivottablecell_transientincidentpivottableparameters
	 */
	public final void setTransientIncidentPivotTableCell_TransientIncidentPivotTableParameters(myfirstmodule.proxies.TransientIncidentPivotTableParameters transientincidentpivottablecell_transientincidentpivottableparameters)
	{
		setTransientIncidentPivotTableCell_TransientIncidentPivotTableParameters(getContext(), transientincidentpivottablecell_transientincidentpivottableparameters);
	}

	/**
	 * Set value of TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters
	 * @param context
	 * @param transientincidentpivottablecell_transientincidentpivottableparameters
	 */
	public final void setTransientIncidentPivotTableCell_TransientIncidentPivotTableParameters(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.TransientIncidentPivotTableParameters transientincidentpivottablecell_transientincidentpivottableparameters)
	{
		if (transientincidentpivottablecell_transientincidentpivottableparameters == null)
			getMendixObject().setValue(context, MemberNames.TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TransientIncidentPivotTableCell_TransientIncidentPivotTableParameters.toString(), transientincidentpivottablecell_transientincidentpivottableparameters.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transientIncidentPivotTableCellMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TransientIncidentPivotTableCell that = (myfirstmodule.proxies.TransientIncidentPivotTableCell) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.TransientIncidentPivotTableCell";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
