// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class TransientRotatedColumnHeaderData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transientRotatedColumnHeaderDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.TransientRotatedColumnHeaderData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RotationDegree("RotationDegree"),
		CellWidth("CellWidth"),
		HeaderHeight("HeaderHeight"),
		HeaderLabelLeft("HeaderLabelLeft"),
		HeaderLabelBottom("HeaderLabelBottom"),
		InputCssTableCell("InputCssTableCell"),
		InputCssHeaderTh("InputCssHeaderTh"),
		InputCssHeaderDiv("InputCssHeaderDiv"),
		InputCssHeaderSpan("InputCssHeaderSpan"),
		ResultCssTableCell("ResultCssTableCell"),
		ResultCssHeaderTh("ResultCssHeaderTh"),
		ResultCssHeaderDiv("ResultCssHeaderDiv"),
		ResultCssHeaderSpan("ResultCssHeaderSpan");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransientRotatedColumnHeaderData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.TransientRotatedColumnHeaderData"));
	}

	protected TransientRotatedColumnHeaderData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transientRotatedColumnHeaderDataMendixObject)
	{
		if (transientRotatedColumnHeaderDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.TransientRotatedColumnHeaderData", transientRotatedColumnHeaderDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.TransientRotatedColumnHeaderData");

		this.transientRotatedColumnHeaderDataMendixObject = transientRotatedColumnHeaderDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransientRotatedColumnHeaderData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TransientRotatedColumnHeaderData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.TransientRotatedColumnHeaderData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TransientRotatedColumnHeaderData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TransientRotatedColumnHeaderData(context, mendixObject);
	}

	public static myfirstmodule.proxies.TransientRotatedColumnHeaderData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TransientRotatedColumnHeaderData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RotationDegree
	 */
	public final Integer getRotationDegree()
	{
		return getRotationDegree(getContext());
	}

	/**
	 * @param context
	 * @return value of RotationDegree
	 */
	public final Integer getRotationDegree(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.RotationDegree.toString());
	}

	/**
	 * Set value of RotationDegree
	 * @param rotationdegree
	 */
	public final void setRotationDegree(Integer rotationdegree)
	{
		setRotationDegree(getContext(), rotationdegree);
	}

	/**
	 * Set value of RotationDegree
	 * @param context
	 * @param rotationdegree
	 */
	public final void setRotationDegree(com.mendix.systemwideinterfaces.core.IContext context, Integer rotationdegree)
	{
		getMendixObject().setValue(context, MemberNames.RotationDegree.toString(), rotationdegree);
	}

	/**
	 * @return value of CellWidth
	 */
	public final Integer getCellWidth()
	{
		return getCellWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of CellWidth
	 */
	public final Integer getCellWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.CellWidth.toString());
	}

	/**
	 * Set value of CellWidth
	 * @param cellwidth
	 */
	public final void setCellWidth(Integer cellwidth)
	{
		setCellWidth(getContext(), cellwidth);
	}

	/**
	 * Set value of CellWidth
	 * @param context
	 * @param cellwidth
	 */
	public final void setCellWidth(com.mendix.systemwideinterfaces.core.IContext context, Integer cellwidth)
	{
		getMendixObject().setValue(context, MemberNames.CellWidth.toString(), cellwidth);
	}

	/**
	 * @return value of HeaderHeight
	 */
	public final Integer getHeaderHeight()
	{
		return getHeaderHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of HeaderHeight
	 */
	public final Integer getHeaderHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.HeaderHeight.toString());
	}

	/**
	 * Set value of HeaderHeight
	 * @param headerheight
	 */
	public final void setHeaderHeight(Integer headerheight)
	{
		setHeaderHeight(getContext(), headerheight);
	}

	/**
	 * Set value of HeaderHeight
	 * @param context
	 * @param headerheight
	 */
	public final void setHeaderHeight(com.mendix.systemwideinterfaces.core.IContext context, Integer headerheight)
	{
		getMendixObject().setValue(context, MemberNames.HeaderHeight.toString(), headerheight);
	}

	/**
	 * @return value of HeaderLabelLeft
	 */
	public final Integer getHeaderLabelLeft()
	{
		return getHeaderLabelLeft(getContext());
	}

	/**
	 * @param context
	 * @return value of HeaderLabelLeft
	 */
	public final Integer getHeaderLabelLeft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.HeaderLabelLeft.toString());
	}

	/**
	 * Set value of HeaderLabelLeft
	 * @param headerlabelleft
	 */
	public final void setHeaderLabelLeft(Integer headerlabelleft)
	{
		setHeaderLabelLeft(getContext(), headerlabelleft);
	}

	/**
	 * Set value of HeaderLabelLeft
	 * @param context
	 * @param headerlabelleft
	 */
	public final void setHeaderLabelLeft(com.mendix.systemwideinterfaces.core.IContext context, Integer headerlabelleft)
	{
		getMendixObject().setValue(context, MemberNames.HeaderLabelLeft.toString(), headerlabelleft);
	}

	/**
	 * @return value of HeaderLabelBottom
	 */
	public final Integer getHeaderLabelBottom()
	{
		return getHeaderLabelBottom(getContext());
	}

	/**
	 * @param context
	 * @return value of HeaderLabelBottom
	 */
	public final Integer getHeaderLabelBottom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.HeaderLabelBottom.toString());
	}

	/**
	 * Set value of HeaderLabelBottom
	 * @param headerlabelbottom
	 */
	public final void setHeaderLabelBottom(Integer headerlabelbottom)
	{
		setHeaderLabelBottom(getContext(), headerlabelbottom);
	}

	/**
	 * Set value of HeaderLabelBottom
	 * @param context
	 * @param headerlabelbottom
	 */
	public final void setHeaderLabelBottom(com.mendix.systemwideinterfaces.core.IContext context, Integer headerlabelbottom)
	{
		getMendixObject().setValue(context, MemberNames.HeaderLabelBottom.toString(), headerlabelbottom);
	}

	/**
	 * @return value of InputCssTableCell
	 */
	public final String getInputCssTableCell()
	{
		return getInputCssTableCell(getContext());
	}

	/**
	 * @param context
	 * @return value of InputCssTableCell
	 */
	public final String getInputCssTableCell(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputCssTableCell.toString());
	}

	/**
	 * Set value of InputCssTableCell
	 * @param inputcsstablecell
	 */
	public final void setInputCssTableCell(String inputcsstablecell)
	{
		setInputCssTableCell(getContext(), inputcsstablecell);
	}

	/**
	 * Set value of InputCssTableCell
	 * @param context
	 * @param inputcsstablecell
	 */
	public final void setInputCssTableCell(com.mendix.systemwideinterfaces.core.IContext context, String inputcsstablecell)
	{
		getMendixObject().setValue(context, MemberNames.InputCssTableCell.toString(), inputcsstablecell);
	}

	/**
	 * @return value of InputCssHeaderTh
	 */
	public final String getInputCssHeaderTh()
	{
		return getInputCssHeaderTh(getContext());
	}

	/**
	 * @param context
	 * @return value of InputCssHeaderTh
	 */
	public final String getInputCssHeaderTh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputCssHeaderTh.toString());
	}

	/**
	 * Set value of InputCssHeaderTh
	 * @param inputcssheaderth
	 */
	public final void setInputCssHeaderTh(String inputcssheaderth)
	{
		setInputCssHeaderTh(getContext(), inputcssheaderth);
	}

	/**
	 * Set value of InputCssHeaderTh
	 * @param context
	 * @param inputcssheaderth
	 */
	public final void setInputCssHeaderTh(com.mendix.systemwideinterfaces.core.IContext context, String inputcssheaderth)
	{
		getMendixObject().setValue(context, MemberNames.InputCssHeaderTh.toString(), inputcssheaderth);
	}

	/**
	 * @return value of InputCssHeaderDiv
	 */
	public final String getInputCssHeaderDiv()
	{
		return getInputCssHeaderDiv(getContext());
	}

	/**
	 * @param context
	 * @return value of InputCssHeaderDiv
	 */
	public final String getInputCssHeaderDiv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputCssHeaderDiv.toString());
	}

	/**
	 * Set value of InputCssHeaderDiv
	 * @param inputcssheaderdiv
	 */
	public final void setInputCssHeaderDiv(String inputcssheaderdiv)
	{
		setInputCssHeaderDiv(getContext(), inputcssheaderdiv);
	}

	/**
	 * Set value of InputCssHeaderDiv
	 * @param context
	 * @param inputcssheaderdiv
	 */
	public final void setInputCssHeaderDiv(com.mendix.systemwideinterfaces.core.IContext context, String inputcssheaderdiv)
	{
		getMendixObject().setValue(context, MemberNames.InputCssHeaderDiv.toString(), inputcssheaderdiv);
	}

	/**
	 * @return value of InputCssHeaderSpan
	 */
	public final String getInputCssHeaderSpan()
	{
		return getInputCssHeaderSpan(getContext());
	}

	/**
	 * @param context
	 * @return value of InputCssHeaderSpan
	 */
	public final String getInputCssHeaderSpan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputCssHeaderSpan.toString());
	}

	/**
	 * Set value of InputCssHeaderSpan
	 * @param inputcssheaderspan
	 */
	public final void setInputCssHeaderSpan(String inputcssheaderspan)
	{
		setInputCssHeaderSpan(getContext(), inputcssheaderspan);
	}

	/**
	 * Set value of InputCssHeaderSpan
	 * @param context
	 * @param inputcssheaderspan
	 */
	public final void setInputCssHeaderSpan(com.mendix.systemwideinterfaces.core.IContext context, String inputcssheaderspan)
	{
		getMendixObject().setValue(context, MemberNames.InputCssHeaderSpan.toString(), inputcssheaderspan);
	}

	/**
	 * @return value of ResultCssTableCell
	 */
	public final String getResultCssTableCell()
	{
		return getResultCssTableCell(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultCssTableCell
	 */
	public final String getResultCssTableCell(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ResultCssTableCell.toString());
	}

	/**
	 * Set value of ResultCssTableCell
	 * @param resultcsstablecell
	 */
	public final void setResultCssTableCell(String resultcsstablecell)
	{
		setResultCssTableCell(getContext(), resultcsstablecell);
	}

	/**
	 * Set value of ResultCssTableCell
	 * @param context
	 * @param resultcsstablecell
	 */
	public final void setResultCssTableCell(com.mendix.systemwideinterfaces.core.IContext context, String resultcsstablecell)
	{
		getMendixObject().setValue(context, MemberNames.ResultCssTableCell.toString(), resultcsstablecell);
	}

	/**
	 * @return value of ResultCssHeaderTh
	 */
	public final String getResultCssHeaderTh()
	{
		return getResultCssHeaderTh(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultCssHeaderTh
	 */
	public final String getResultCssHeaderTh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ResultCssHeaderTh.toString());
	}

	/**
	 * Set value of ResultCssHeaderTh
	 * @param resultcssheaderth
	 */
	public final void setResultCssHeaderTh(String resultcssheaderth)
	{
		setResultCssHeaderTh(getContext(), resultcssheaderth);
	}

	/**
	 * Set value of ResultCssHeaderTh
	 * @param context
	 * @param resultcssheaderth
	 */
	public final void setResultCssHeaderTh(com.mendix.systemwideinterfaces.core.IContext context, String resultcssheaderth)
	{
		getMendixObject().setValue(context, MemberNames.ResultCssHeaderTh.toString(), resultcssheaderth);
	}

	/**
	 * @return value of ResultCssHeaderDiv
	 */
	public final String getResultCssHeaderDiv()
	{
		return getResultCssHeaderDiv(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultCssHeaderDiv
	 */
	public final String getResultCssHeaderDiv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ResultCssHeaderDiv.toString());
	}

	/**
	 * Set value of ResultCssHeaderDiv
	 * @param resultcssheaderdiv
	 */
	public final void setResultCssHeaderDiv(String resultcssheaderdiv)
	{
		setResultCssHeaderDiv(getContext(), resultcssheaderdiv);
	}

	/**
	 * Set value of ResultCssHeaderDiv
	 * @param context
	 * @param resultcssheaderdiv
	 */
	public final void setResultCssHeaderDiv(com.mendix.systemwideinterfaces.core.IContext context, String resultcssheaderdiv)
	{
		getMendixObject().setValue(context, MemberNames.ResultCssHeaderDiv.toString(), resultcssheaderdiv);
	}

	/**
	 * @return value of ResultCssHeaderSpan
	 */
	public final String getResultCssHeaderSpan()
	{
		return getResultCssHeaderSpan(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultCssHeaderSpan
	 */
	public final String getResultCssHeaderSpan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ResultCssHeaderSpan.toString());
	}

	/**
	 * Set value of ResultCssHeaderSpan
	 * @param resultcssheaderspan
	 */
	public final void setResultCssHeaderSpan(String resultcssheaderspan)
	{
		setResultCssHeaderSpan(getContext(), resultcssheaderspan);
	}

	/**
	 * Set value of ResultCssHeaderSpan
	 * @param context
	 * @param resultcssheaderspan
	 */
	public final void setResultCssHeaderSpan(com.mendix.systemwideinterfaces.core.IContext context, String resultcssheaderspan)
	{
		getMendixObject().setValue(context, MemberNames.ResultCssHeaderSpan.toString(), resultcssheaderspan);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transientRotatedColumnHeaderDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TransientRotatedColumnHeaderData that = (myfirstmodule.proxies.TransientRotatedColumnHeaderData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.TransientRotatedColumnHeaderData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
