// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package profileservice.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the ProfileService module
	public static java.lang.String getDisplayName(IContext context, java.lang.String _openID, java.lang.String _environmentPassword, java.lang.String _environmentUUID)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("OpenID", _openID);
			params.put("EnvironmentPassword", _environmentPassword);
			params.put("EnvironmentUUID", _environmentUUID);
			return (java.lang.String)Core.execute(context, "ProfileService.GetDisplayName", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}